### PR TITLE
Pages table refactor my and access

### PR DESCRIPTION
**Pull request by hannahkamundson**
Changes so it has a "my" page (linked to gsndb/my) and "all" page (linked to gsndb/all).

### CODE REVIEW

**Comment by hannahkamundson** [comment]
Ok @HTempleman look at it now

**Comment by HTempleman** [comment]
Final note after review:

Although I requested changes. I'm willing to eschew these requests if either of you feel that they would unduly stymie project momentum. I would, however, appreciate a brief explanation of your reasoning.

**Comment by hannahkamundson** [comment]
Ps this is between you and Brenden and whatever he wants so wait for his response! My only comment is since the note feature is related to a different pull request I think it is better to make it an issue

**Comment by hannahkamundson** [comment]
Also last comment. I personally find it less readable to put hooks in the routes but you and brenden can decide what you want

**Comment by bthornton505** [comment]
UPDATE

1. I made the changes Hunter proposed to reduce the bloat of the my/all feature. I was able to change our routes to render the same component, such as <Students />, and pass in the MY_CONST or ALL_CONST prop to allow it to properly render with corresponding data. I needed to change our routes to <Route /> instead of <PrivateRoute /> to allow for this change. I don't believe we lose any functionality with that specific change. Overall this allowed us to take away all the individual <MyComponentt /> and <AllComponent /> components and only render the ones we had previously created. It's the same logic Hannah created but this will allow for better readability and one less step for our app to process. 

Hannah: I know I talked about using Hooks to make this above change possible but Hunter provided an idea that I was also familiar with and is much easier to read. We aren't using Hooks to pass these props and instead use the ability of React Router to pass the props we need when the route renders the component. I will happily explain how this works next meeting if you have any questions. 

2. I updated all the components to use camelCase instead of snake_case. This is standard practice for writing JavaScript and we all need to make sure we are following best practices. 

3. I also added comments in our table components (Students, Courses, Programs, etc.) to explain the variables being created at the top of the component. I also arranged them in a specific order so there can be consistency when making refactors and make readability more clear. 

4. Hunter I think the other points you brought up are valid and need to be looked at, but I think we can make separate issues for those after we merge this branch. They feel like performance issues that might need to be resolved on both sides of the stack. With more digging into them I'm sure we can find a good solution to make these features smoother. 

Let me know what you guys think of my changes and hopefully we can get this merged later today!

**Pull request merged**
