### PR TITLE
Create nested pages

### PR DESCRIPTION
**Pull request by hannahkamundson**
Added nested pages & created some components for tables & styles so that it is more organized. 
Attendance pages are being a pain so still need to play with them. Believe I still need to make behavior pages.

### CODE REVIEW

**Comment by hannahkamundson** [comment]
Ok I’ll figure out what’s going on with attendance and then submit the pull request. 
I was creating a function with a switch statement but after talking with David we decided it wasn’t readable and it was better to just split it into a few functions. Especially once I saw that there is actually very little about the table code that is actually the same. Lmk what you think.
So are you saying you don’t want the various pages/tables to be structured the way they were before I added stuff?

**Comment by HTempleman** [comment]
The earlier table(s) were constructed much more explicitly, but they were also constructed when there weren't enough tables to justify a generalization. Currently, you have 27 components in your tables directory. I believe that definitely warrants generalization. To be clear, you had to create them for us to have a better idea of how they should be generalized! I set up a tally list that separates table creation by import statement:

- import { DetailLink, DetailItem} (5)
- import {CreateStudentTable} (5)
- import {CreateGradeTable} (5)
- import {CreateCourseTable} (4)
- import {CreateAttendanceTable} (3)
- import {CreateProgramTable} (1)
- import {CreateSchoolTable} (2)

Using these import statements as a guide, we could make seven (or eight when taking the CreateDistrictTable component into account) generic Table components. This is significantly less than the 27 that are currently available to us. Though those 7/8 components will be more complex, they will be easier to review by virtue of there being less, and they will be easier to debug because we won't have to juggle so many tables when something goes wrong. 

The tallies there don't add up to 27, likely because I lost track of things when I got distracted revisiting prior components to understand the purpose of certain other import statements that are called but never used. For example, both StudentAttendanceDetail and StudentDistrictDetail are making the following import statement:

import {
   Table, TableBody, TableCell, etc...
} 

But they never use any of these. This suggests that you were reusing code (often a good idea!) but neglecting to delete these import statements, which injects confusion into the review process. Also, it appears that you've made a CreateDistrictTable but chose not to use it in Districts.js. 

I would suggest one of two directions going forward:

1. Close this pull request and create a bunch of separate pull requests in which you focus on integrating one table at a time. (i.e. a pull request for and DetailLinks/DetailItems, one for CourseTables, one for AttendanceTables, etc...).
2. Close this pull request and create a bunch of separate pull requests in which you follow the above suggestion and also implement a generic routine outlined earlier. This would definitely require coordination with Brenden!

Doing either of the above will result in your code being merged quicker. While choosing the ladder option may take more up-front time to code, it should be easier for me to review and more maintainable in the long-run. Out of curiosity, how were you constructing the switch statement that you attempted earlier? Were you checking state or trying to inspect the data that was passed? The latter really would be an awful and tedious approach, in which case I certainly wouldn't fault you for the process you've chosen! I'm unaware of whether we have state constants that describe current app attributes (i.e. student & attendance -- district & attendance -- District & Course -- etc)

I think it's worth reiterating here that these questions wouldn't even be coming up had you not put in the work and made this pull request.

**Comment by hannahkamundson** [comment]
Ok I like the idea of creating some of those tables as methods. After seeing how we are wanting the pages to look, I’m going to do a little moving so that there should only be two pages per thing as well.
As for the making the CreateAttendanceTable and CreateStudentTable the same, I don’t understand the question. All I know is when I was talking to David he emphasized readability. If you have a readable way to pass in headers and each column type I’ll do it. Otherwise I’ll keep it the way it is

**Comment by HTempleman** [comment]
In a nutshell, I currently don't want to conflate any of your "Create" components. I agree that doing so would likely be more confusing than helpful in the short run. Once we generalize the Tables that are invoking your "Create" components (see my tally list) we can consider whether that would be helpful, though I'm definitely leaning more towards keeping them separate. Honestly, I have the suspicion that after we generalize your "Table" components, we'll realize that we can just fold their code into the code for the "Create" components, but I'd hold off on making that leap until after we see what the generalized table components look like. 

Going over my thought process, I think my suggestions are incidentally in line with Brenden's ideas. I think our tentative plan going forward will have him running interference on Redux stuff so that we can adapt the Application as more components are thrown into the mix. I'd recommend broaching these subjects with him on discord or in person so that y'all can flesh out some ideas. 

As I mentioned, I would much prefer pulling a smaller set of commits than what we currently have on hand. My off the cuff suggestion would be to make separate branches that incorporate the following aspects of your changes:

1. Styles *
2. Routes
3. Creation Components *
4. Mock Data

Just an idea to work off of, you may discover a better way to break things apart. I've starred the portions I think are most significant. I haven't really looked at how styles work in our project, so I'd love an opportunity to go over your changes and get a better handle on our aesthetics! I also believe your Creation Components seem sensible and would serve as a great foundation.

I didn't star the Routes and the mock data because they are only required for the Tables that are hopefully going to be generalized. When pushing a generic table, it may make more sense to add a single route and the requisite mock data. Ideally, you'd be using the data from our test server. This would be a good opportunity for you to establish parallel sprints with Brenden where he constructs a proper fetch statement for you to utilize in your generic table. If you need to use your own frontend mock data while Brenden is busy constructing a request, that is completely understandable. 

Our first order of Redux business will likely involve storing application attribute state. Say you're working on creating a generic table, you'll need to know the attribute the table describes. Is it Attendance for a School or Attendance for a Student? I believe we'll need this feature in place before we can start incorporating generic tables. A perfect issue to create and assign to Brenden!

 If you think that it will be difficult to separate these commits into different pull requests, that's understandable. For the remainder of your changes, I would encourage you to push an updated version of this branch to the repo so that it's backed up, and then begin the process of peeling off some of it's functionality into smaller branches for bite-sized PRs. A good hard and fast rule of thumb may be that pull requests should solve a maximum of two posted issues. If you're wanting to make a pull request that solves an issue that you've discovered, but it hasn't been posted, then you should create the issue and [attach it to your commit/PR ](https://github.blog/2013-05-14-closing-issues-via-pull-requests/)so that you're self-regulating how much code you push in a single PR. 

Given these points, would you be okay if I closed this PR?

**Comment by hannahkamundson** [comment]
Yep go ahead

**Pull request closed without merging**
