### PR TITLE
Add search component

### PR DESCRIPTION
**Pull request by kmid5280**
Any feedback regarding initial implementation of the nav bar link and search component welcome. Component style and redux hookup still need to be worked out.

### CODE REVIEW

**Comment by kmid5280** [comment]
@HTempleman Thanks for the response. My first question is, how far into the redux would you like me to go? I'm happy to do it, but I'm still a little bit green with redux and would need to familiarize myself with your code somewhat. If you want me to switch it to a hook I could see about implementing that, or I could move onto a different issue if you'd rather delegate that elsewhere.

**Comment by HTempleman** [comment]
If you are interested in exploring redux hooks further, I would encourage you to first create a requisite reducer and action (i.e. searchAction.js & searchReducer.js) and then employ a useDispatch() hook to dispatch your queries to the store. It may be helpful to look over the actions and reducers that are presently in the 'state' directory to get a feel for how things are presently structured. 

Also, is this related to [issue#13](https://github.com/codefordenver/gsn-frontend/issues/13), or are you solving a different problem, like trying to query the API itself? I don't want to delegate until I'm certain of the goal.

**Comment by kmid5280** [comment]
@HTempleman I'm not aware of whether or not it's related to that issue. All I understand so far is that you needed to put together a search component and that it will be connected via redux.

**Comment by HTempleman** [comment]
@kmid5280 Understood. I would suggest that you reach out to the person who outlined the initial goals of the search component and determine what is being searched and why redux is necessary. I can envision some scenarios where redux would be needed for storing search queries, and others where it would be unnecessary overhead. If you would prefer to move on to another issue, we can have @bthornton505 work on drawing up the redux logic whenever he has the time. 

In either case, I would discourage redux-form going forward and emphasize that redux interactions should strictly be done through hooks, if only for the sake of consistency.

**Comment by hannahkamundson** [comment]
Hey @bthornton505. Finished this up. Kyle put it on the left nav. I made it so it populates results as long as the search isn't empty. Let me know what you think or any modifications needed, specifically with style because I was just making that up lol

**Pull request merged**
