### PR TITLE
Redux add referral

### PR DESCRIPTION
**Pull request by hannahkamundson**
Made the pull request for Josh & reviewed it (he did the commits)

Guess I still need someone to approve it since I made the request.

He just added in the referral entering component on the student detail page

### CODE REVIEW

**Comment by jberns** [comment]
@bthornton505 

The frontend is mostly working in regards to data sending and fetching but the backend needs to be updated to support this properly, as you mentioned the correct data is not coming back so all of the regular student data is being removed.  Here were some of my notes that I left in the referral.js file.

  //! 1. Need program to be sent as part of student details
  //! 2. Need referral to send back student data based on ID
  //! 3. Need to setup form validation
  //! 4. Referral table needs to be populated based on returned student data

I think you can either leave this open until the backend is updated or merge and make some additional issues to go back and fix this.

**Comment by hannahkamundson** [comment]
@bthornton505  The issue with this is backend not frontend. Currently the referral table isn't populated because the backend is still waiting for approval to add that change to the endpoint (or maybe Ivan approved it and I just need to push it up). If you want to see what it is doing, type something in and then go to gsndev.com/gsndb/all/referral and you will see your note

**Comment by bthornton505** [comment]
Also, if these issues are expected because we just want to get the barebones of the new feature out and then they'll be resolved with a future change on the backend then that sounds okay to me. Just want to get some clarity around this feature before approving and merging.

**Comment by hannahkamundson** [comment]
My vote is push it up  backend is in the process

**Pull request merged**
